# Generated by Django 4.0.5 on 2022-08-25 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_chat_options_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='chats',
        ),
        migrations.AddField(
            model_name='user',
            name='chat_with',
            field=models.ManyToManyField(blank=True, related_name='Chat_with', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='last_used',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
