# Generated by Django 4.0.5 on 2022-08-25 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_user_chats_user_chat_with_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
