# Generated by Django 4.1.3 on 2023-06-12 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_chatmessage_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='author',
        ),
    ]
